/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kkp;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rezabdullah
 */
public class Delivery extends javax.swing.JFrame {
    int idShipping;
    
    private void showData(int id){        
        try{
            java.sql.Connection con = Database.ConnectDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery("select s.id, c.nama as `sender_name`, s.recipient_name, s.recipient_address, s.recipient_phone, s.item_name, s.item_weight, s.item_qty, p.nama as `pack_name`, s.pack_qty, s.ship_type, s.amount, a.fullname as `officer`, sp.status, .sp.note from shipping s inner join admin a on s.id_sender = a.id inner join customer c on s.id_sender = c.id inner join pack p on s.id_pack = p.id inner join shipping_detail sp on s.id = sp.id_shipping where s.id = '" + id + "'");
            
            if(res.next()){
                this.idShipping = id;
                
                labelSenderData.setText(res.getString("sender_name"));
                labelRecipientData.setText(res.getString("recipient_name"));
                labelAddressData.setText(res.getString("recipient_address"));
                labelPhoneData.setText(res.getString("recipient_phone"));
                labelItemNameData.setText(res.getString("item_name"));
                labelItemWeightData.setText(res.getString("item_weight"));
                labelItemQtyData.setText(res.getString("item_qty"));
                labelPackNameData.setText(res.getString("pack_name"));
                labelPackQtyData.setText(res.getString("pack_qty"));
                labelShippingTypeData.setText(res.getString("ship_type"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void setAWB()
    {        
        try{
            java.sql.Connection con = Database.ConnectDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery("select id from shipping");
            
            while(res.next()){
                int index = Integer.parseInt(res.getString(1));
                String name = res.getString(1);
                SetComboBoxValue data = new SetComboBoxValue(index,name);
                inputAWB.addItem(data);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Creates new form Delivery
     */
    public Delivery() {
        initComponents();
        setAWB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelItemQuantity = new javax.swing.JLabel();
        labelPackingType = new javax.swing.JLabel();
        labelPackQuantity = new javax.swing.JLabel();
        labelShippingType = new javax.swing.JLabel();
        labelNote = new javax.swing.JLabel();
        labelItemName = new javax.swing.JLabel();
        inputNote = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelAdminTitle = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        labelSender = new javax.swing.JLabel();
        labeAddress = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelRecipient = new javax.swing.JLabel();
        labelItemWeight = new javax.swing.JLabel();
        labelRecipientData = new javax.swing.JLabel();
        labelAddressData = new javax.swing.JLabel();
        labelPhoneData = new javax.swing.JLabel();
        labelSenderData = new javax.swing.JLabel();
        labelItemNameData = new javax.swing.JLabel();
        labelItemWeightData = new javax.swing.JLabel();
        labelPackNameData = new javax.swing.JLabel();
        labelItemQtyData = new javax.swing.JLabel();
        labelShippingTypeData = new javax.swing.JLabel();
        labelPackQtyData = new javax.swing.JLabel();
        btnUpdateStatus = new javax.swing.JButton();
        labelSender1 = new javax.swing.JLabel();
        inputAWB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelItemQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelItemQuantity.setText("Item Quantity");

        labelPackingType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPackingType.setText("Packing");

        labelPackQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPackQuantity.setText("Pack Quantity");

        labelShippingType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelShippingType.setText("Shipping Type");

        labelNote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNote.setText("Note");

        labelItemName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelItemName.setText("Item Name");

        inputNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 59, 87));

        labelAdminTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelAdminTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelAdminTitle.setText("RECEIVING");

        btnback.setBackground(new java.awt.Color(245, 59, 87));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdminTitle)
                .addGap(628, 628, 628))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdminTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelSender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSender.setText("Sender");

        labeAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labeAddress.setText("Address");

        labelPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPhone.setText("Phone Number");

        labelRecipient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRecipient.setText("Recipient");

        labelItemWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelItemWeight.setText("Item Weight");

        labelRecipientData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRecipientData.setText("-");

        labelAddressData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAddressData.setText("-");

        labelPhoneData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPhoneData.setText("-");

        labelSenderData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSenderData.setText("-");

        labelItemNameData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelItemNameData.setText("-");

        labelItemWeightData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelItemWeightData.setText("-");

        labelPackNameData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPackNameData.setText("-");

        labelItemQtyData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelItemQtyData.setText("-");

        labelShippingTypeData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelShippingTypeData.setText("-");

        labelPackQtyData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPackQtyData.setText("-");

        btnUpdateStatus.setBackground(new java.awt.Color(245, 59, 87));
        btnUpdateStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("UPDATE STATUS");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        labelSender1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSender1.setText("AWB");

        inputAWB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAWBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdateStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelPhoneData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(labelRecipient, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labeAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelRecipientData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddressData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelSenderData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelSender1)
                            .addComponent(labelSender)
                            .addComponent(inputAWB, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelItemName)
                            .addComponent(labelItemWeight)
                            .addComponent(labelItemQuantity)
                            .addComponent(labelPackingType)
                            .addComponent(labelNote)
                            .addComponent(labelPackQuantity)
                            .addComponent(labelShippingType)
                            .addComponent(inputNote, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(labelItemNameData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelItemWeightData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPackNameData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelItemQtyData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelShippingTypeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPackQtyData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(865, 865, 865))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelItemName)
                    .addComponent(labelSender1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAWB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemNameData))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelItemWeight)
                        .addGap(9, 9, 9)
                        .addComponent(labelItemWeightData)
                        .addGap(18, 18, 18)
                        .addComponent(labelItemQuantity)
                        .addGap(9, 9, 9)
                        .addComponent(labelItemQtyData)
                        .addGap(18, 18, 18)
                        .addComponent(labelPackingType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPackNameData)
                        .addGap(23, 23, 23)
                        .addComponent(labelPackQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPackQtyData)
                        .addGap(28, 28, 28)
                        .addComponent(labelShippingType)
                        .addGap(18, 18, 18)
                        .addComponent(labelShippingTypeData)
                        .addGap(16, 16, 16)
                        .addComponent(labelNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelSender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSenderData)
                        .addGap(16, 16, 16)
                        .addComponent(labelRecipient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRecipientData)
                        .addGap(16, 16, 16)
                        .addComponent(labeAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAddressData)
                        .addGap(16, 16, 16)
                        .addComponent(labelPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPhoneData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoteActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        try{
            java.sql.Connection con = Database.ConnectDB();
            java.sql.PreparedStatement stm = con.prepareStatement("INSERT INTO shipping_detail VALUES(null, '" + this.idShipping +
                    "', '" + Session.id + "', 'delivered', '" + inputNote.getText() + "')");
            stm.execute();

            JOptionPane.showMessageDialog(null, "Data tersimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void inputAWBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAWBActionPerformed
        SetComboBoxValue getInputSender = (SetComboBoxValue) inputAWB.getSelectedItem();
        int awb = getInputSender.GetIndex();
        
        showData(awb);
    }//GEN-LAST:event_inputAWBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Delivery Page = new Delivery();
                Page.setVisible(true);
                Page.setExtendedState(Page.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<SetComboBoxValue> inputAWB;
    private javax.swing.JTextField inputNote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeAddress;
    private javax.swing.JLabel labelAddressData;
    private javax.swing.JLabel labelAdminTitle;
    private javax.swing.JLabel labelItemName;
    private javax.swing.JLabel labelItemNameData;
    private javax.swing.JLabel labelItemQtyData;
    private javax.swing.JLabel labelItemQuantity;
    private javax.swing.JLabel labelItemWeight;
    private javax.swing.JLabel labelItemWeightData;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelPackNameData;
    private javax.swing.JLabel labelPackQtyData;
    private javax.swing.JLabel labelPackQuantity;
    private javax.swing.JLabel labelPackingType;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPhoneData;
    private javax.swing.JLabel labelRecipient;
    private javax.swing.JLabel labelRecipientData;
    private javax.swing.JLabel labelSender;
    private javax.swing.JLabel labelSender1;
    private javax.swing.JLabel labelSenderData;
    private javax.swing.JLabel labelShippingType;
    private javax.swing.JLabel labelShippingTypeData;
    // End of variables declaration//GEN-END:variables
}
